export const BOOKS = [
  ['To Each His Own', 'Leonardo Sciascia'],
  ['The Mousetrap', 'Agatha Christie'],
  ['One, No One and One Hundred Thousand', 'Luigi Pirandello'],
  ['The Little Prince', 'Antoine de Saint-Exupéry'],
  ['The Metamorphosis', 'Franz Kafka'],
  ['Siddhartha', 'Hermann Hesse'],
  ['White Nights', 'Fyodor Dostoevsky'],
  ['The Name of the Rose', 'Umberto Eco'],
  ['Fahrenheit 451', 'Ray Bradbury'],
  ['The Sorrows of Young Werther', 'Johann Wolfgang von Goethe'],
  ['Spoon River Anthology', 'Edgar Lee Masters'],
  ['Moby-Dick', 'Herman Melville'],
  ['Sixty Stories', 'Dino Buzzati'],
  ['Don Quixote', 'Miguel de Cervantes'],
  ['The Life of Don Quixote and Sancho', 'Miguel de Unamuno'],
  ['The Brothers Karamazov', 'Fyodor Dostoevsky'],
  ['Brief Interviews with Hideous Men', 'David Foster Wallace'],
  ['Nausea', 'Jean-Paul Sartre'],
  ['The Wall', 'Jean-Paul Sartre'],
  ['The Man Who Mistook His Wife for a Hat', 'Oliver Sacks'],
  ['This Is Water', 'David Foster Wallace'],
  ['Doctor Faustus', 'Christopher Marlowe'],
  ['The Stranger', 'Albert Camus'],
  ['Anna Karenina', 'Leo Tolstoy'],
  ['Life of a Man', 'Giuseppe Ungaretti'],
  ['Cuttlefish Bones', 'Eugenio Montale'],
  ['A Love Affair', 'Dino Buzzati'],
  ['The Day of the Owl', 'Leonardo Sciascia'],
  ['The Chimera', 'Sebastiano Vassalli'],
  ['The Grapes of Wrath', 'John Steinbeck'],
  ['The Book of Disquiet', 'Fernando Pessoa'],
  ['The Tartar Steppe', 'Dino Buzzati'],
  ['Two Women', 'Alberto Moravia'],
  ['The Call of the Wild', 'Jack London'],
  ['Green Parrots', 'Gino Strada'],
  ['Elective Affinities', 'Johann Wolfgang von Goethe'],
  ['Slaughterhouse-Five', 'Kurt Vonnegut'],
  ['One Hundred Love Poems to Ladyhawke', 'Michele Mari'],
  ['Quo Vadis', 'Henryk Sienkiewicz'],
  ['The Selfish Gene', 'Richard Dawkins'],
  ['A Fortune-Teller Told Me', 'Tiziano Terzani'],
  ['Infinite Jest', 'David Foster Wallace'],
  ['The Clown', 'Heinrich Böll'],
  ["Man's Search for Meaning", 'Viktor E. Frankl'],
  ['Do Androids Dream of Electric Sheep?', 'Philip K. Dick'],
  ['Entangled Life', 'Merlin Sheldrake'],
  ['The Aleph', 'Jorge Luis Borges'],
  ['Both Flesh and Not', 'David Foster Wallace'],
  ["A Supposedly Fun Thing I'll Never Do Again", 'David Foster Wallace'],
  ['The Unbearable Lightness of Being', 'Milan Kundera'],
  ['The Cheese and the Worms', 'Carlo Ginzburg'],
  ['Bebelplatz: The Night of the Book Burnings', 'Fabio Stassi'],
  ['Todo Modo', 'Leonardo Sciascia'],
  ['Fontamara', 'Ignazio Silone'],
  ['Babi Yar', 'Anatoly Kuznetsov'],
  ['The Men with the Pink Triangle', 'Heinz Heger'],
  ['The Sergeant in the Snow', 'Mario Rigoni Stern'],
  ['If This Is a Man', 'Primo Levi'],
  ['The Truce', 'Primo Levi'],
  ['Eichmann in Jerusalem: A Report on the Banality of Evil', 'Hannah Arendt'],
  ['The Drowned and the Saved', 'Primo Levi'],
  ['Father Sergius', 'Leo Tolstoy'],
  ['Consider the Lobster', 'David Foster Wallace'],
  ['The Gold-Rimmed Spectacles', 'Giorgio Bassani'],
  ['The Disappearance of Majorana', 'Leonardo Sciascia'],
  ['To Kill a Mockingbird', 'Harper Lee'],
  ['The Tragedy of Human Existence', 'Miguel de Unamuno'],
  ['Three Men in a Boat', 'Jerome K. Jerome'],
  ['The Little Dog', 'Vasily Grossman'],
  ['The Devil', 'Leo Tolstoy'],
  ['The Watcher', 'Italo Calvino'],
] as const;
