export const SITE = {
  name: 'Riccardo Rasoni',
  title: 'Riccardo Rasoni | Economics Research',
  description: 'Riccardo Rasoni is a PhD candidate in Economics at the University of Padua. Research in macroeconomics, survey analysis, and household expectations.',
  url: 'https://riccardorasoni-debug.github.io',
  email: 'riccardo.rasoni@phd.unipd.it',
  personalEmail: 'riccardorasoni@gmail.com',
  github: 'https://github.com/riccardorasoni-debug',
  institution: 'University of Padua',
  department: 'Department of Economics and Management “Marco Fanno”',
  streetAddress: 'Via del Santo 33',
  postalCode: '35123',
  city: 'Padua',
  country: 'Italy',
};
